/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#00677f',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        secondary: '#565e74',
        'on-secondary-container': '#5c647a',
        'error-container': '#ffdad6',
        outline: '#6c797f',
        background: '#f7f9fb',
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'on-secondary-fixed': '#131b2e',
        'surface-container-highest': '#e0e3e5',
        'secondary-container': '#dae2fd',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-container': '#005a3c',
        'on-secondary-fixed-variant': '#3f465c',
        'inverse-primary': '#4cd6ff',
        surface: '#f7f9fb',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary-fixed-variant': '#005236',
        'primary-fixed': '#b7eaff',
        'surface-tint': '#00677f',
        'on-surface-variant': '#3c494e',
        'tertiary-container': '#46d89d',
        'tertiary-fixed-dim': '#4edea3',
        'primary-container': '#00d1ff',
        error: '#ba1a1a',
        'on-surface': '#191c1e',
        'on-primary-fixed': '#001f28',
        'outline-variant': '#bbc9cf',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'inverse-surface': '#2d3133',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#4cd6ff',
        'on-primary-container': '#00566a',
        'on-primary-fixed-variant': '#004e60',
        'on-background': '#191c1e',
        'on-error': '#ffffff',
        'surface-container': '#eceef0',
        'surface-dim': '#d8dadc',
        tertiary: '#006c49',
        'secondary-fixed-dim': '#bec6e0',
        'secondary-fixed': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '24px',
        margin: '32px',
        unit: '8px',
        'container-max': '1440px',
        'stack-lg': '32px',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'data-mono': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '1', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default config;
